name: Lint, Test and Deploy sequentially
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
  test: 
    needs: lint
    runs-on: ubuntu-latest
    steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: Test
              run: npm run test
  deploy: 
    needs: test
    runs-on: ubuntu-latest
    steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "....Displaying together"
  
      
       